install:
- sudo apt-get update -qq
- sudo apt-get install -y pandoc texlive-full texlive-xetex
- chmod u+x .ci/update_build.sh

env:
  - BUILD_TIME=$(TZ=Asia/Hong_Kong date)

script: make travis

after_success:
  - bash .ci/update_build.sh
  - echo $BUILD_TIME
