language: c

addons:
  apt:
    update: true
    packages:
    - pandoc
    - texlive-full
    - texlive-xetex

before_script:
  - export TZ=Asia/Hong_KONG
  - BUILD_TIME=$(TZ=Asia/Hong_Kong date '+%a %d %b %Y %T %Z')
#  - ADMIN=`ls openlex-admin`
#  - CONS=`ls openlex-cons`
#  - CONTRACT=`ls openlex-contract`
#  - CRIM=`ls openlex-crim`
#  - EQUITY=`ls openlex-equity`
#  - LAND=`ls openlex-land`
#  - TORT=`ls openlex-tort`

script: make all

before_deploy:
  - chmod u+x .ci/update_build.sh

deploy:
  provider: script
  script: .ci/update_build.sh
  skip_cleanup: true
  on:
    branch: master
