language: c
sudo: true

cache:
  directories:
  - $HOME/.stack
  
addons:
  apt:
    packages:
    - libgmp-dev
    - xzdec
    
before_install:
- mkdir -p $HOME/.local/bin
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
- stack setup
- stack install pandoc
script: make travis
notifications:
  email:
    on_success: always
    on_failure: always
after_success: bash .ci/update_pages.sh
